spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G9LcAjanmnn4oCgodL7
      secret-key: faofyfy6Cok0mTtFJMN8wThwErT3Ey
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: edu-wyf

  application:
    name: gulimall-third-party

server:
  port: 30000
